enabled: true
tagline: 'Atelier vélo participatif libre et ouvert'
footer_columns:
  -
    content: "### Association\r\n\r\n[La boite à Cycler](/) est une association Loi 1901.\r\n\r\n* [Statuts](/statuts)\r\n* [Réglement intérieur](/reglement-interieur)\r\n* [Adhérer à l'association](/bulletin-d-adhesion)"
  -
    content: "### Contact\r\n\r\nVous pouvez bien évidemment [nous écrire](mailto:contact@laboiteacycler.org) mais nous préférons rencontrer les gens lors des nombreux événements et discuter de vive voix !"
  -
    content: "### Adhérents et bénévoles\r\n\r\n2 listes de diffusion vous sont réservées, l'une pour tous les adhérents, l'autre pour les adhérents bénévoles. \r\nSi vous n'y avez pas été inscrits lors de votre adhésion, [rappelez-le nous par email](mailto:contact@laboiteacycler.org).\r\n\r\n[Accéder à l'administration du site](/admin)."
google_webmaster_tools_id: 0CY7SekIV4chY46zydcRPoV0Da0hNKiHEfIwndFuqx8
background:
  user/themes/boiteacycler/assets/P1080646-2000px-50p.jpg:
    name: P1080646-2000px-50p.jpg
    type: image/jpeg
    size: 704893
    path: user/themes/boiteacycler/assets/P1080646-2000px-50p.jpg
