enabled: true
tagline: 'Atelier vélo participatif libre et ouvert'
footer_columns:
  -
    content: "### Association\r\n\r\n[La boite à Cycler](/) est une association Loi 1901.\r\n\r\n* [Statuts](/statuts)\r\n* [Réglement intérieur](/reglement-interieur)\r\n* [Adhérer à l'association](/bulletin-d-adhesion)"
  -
    content: "### Contact\r\n\r\nVous pouvez bien évidemment [nous écrire](mailto:contact@laboiteacycler.org) mais nous préférons rencontrer les gens lors des nombreux événements et discuter de vive voix !"
  -
    content: "### Adhérents et bénévoles\r\n\r\n[Un site](http://) est dédié à l'organisation de toutes les activités de l'association. L'accès est privé, si vous n'y avez pas encore accès n'hésitez pas à nous relancer.\r\n\r\n[Accéder à l'administration du site](/admin)."
google_webmaster_tools_id: 0CY7SekIV4chY46zydcRPoV0Da0hNKiHEfIwndFuqx8
