title: 'La boîte à Cycler'
default_lang: fr
author:
  name: 'La boîte à Cycler'
  email: contact@laboiteacycler.org
taxonomies:
  - category
  - tag
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
